# -*- coding: utf-8 -*-
"""c_strength.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dZYSUyJaeMs2PI76dDaYE3Fn8QOLkfog
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

from sklearn.neural_network import MLPRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from scipy.optimize import minimize

df=pd.read_csv("/content/sample_data/c_strength.csv")

df.info()

df.columns

df["Log_Bacterial_Concentration"] = np.log10(
    df["Bacterial Concentration (cells/mL)"].replace(0, 1)
)

X = df[
    [
        "Concrete Type",
        "Curing Age (Days)",
        "Cement",
        "Bacteria",
        "Log_Bacterial_Concentration"
    ]
]

y = df["Compressive Strength (MPa)"]

plt.figure()
plt.hist(y, bins=15)
plt.xlabel("Compressive Strength (MPa)")
plt.ylabel("Frequency")
plt.title("Distribution of Compressive Strength")
plt.show()

categorical_features = ["Concrete Type", "Cement", "Bacteria"]
numerical_features = ["Curing Age (Days)", "Log_Bacterial_Concentration"]

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_features),
        ("cat", OneHotEncoder(drop="first", handle_unknown="ignore",
                              categories=[
                                  ['Normal Concrete', 'Bacterial Concrete'],
                                  ['OPC 53 (UltraTech)'],
                                  ['Control', 'Bacillus subtilis']
                              ]),
         categorical_features)
    ]
)

rf_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(
        n_estimators=500,
        random_state=42
    ))
])

rf_pred = cross_val_predict(rf_model, X, y, cv=5)

print("RF R2   :", r2_score(y, rf_pred))
print("RF RMSE :", np.sqrt(mean_squared_error(y, rf_pred)))

plt.figure()
plt.scatter(y, rf_pred)
plt.plot([y.min(), y.max()], [y.min(), y.max()])
plt.xlabel("Actual Compressive Strength")
plt.ylabel("Predicted Compressive Strength")
plt.title("Random Forest: Actual vs Predicted")
plt.show()



"""####SVR

"""

svr_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", SVR(
        kernel="rbf",
        C=100,
        epsilon=0.1
    ))
])

svr_pred = cross_val_predict(svr_model, X, y, cv=5)

print("SVR R2   :", r2_score(y, svr_pred))
print("SVR RMSE :", np.sqrt(mean_squared_error(y, svr_pred)))

plt.figure()
plt.scatter(y, svr_pred)
plt.plot([y.min(), y.max()], [y.min(), y.max()])
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.title("SVR: Actual vs Predicted")
plt.show()

ann_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", MLPRegressor(
        hidden_layer_sizes=(32, 16),
        activation="relu",
        alpha=0.001,
        max_iter=5000,
        random_state=42
    ))
])

ann_pred = cross_val_predict(ann_model, X, y, cv=5)

print("ANN R2   :", r2_score(y, ann_pred))
print("ANN RMSE :", np.sqrt(mean_squared_error(y, ann_pred)))

plt.figure()
plt.scatter(y, ann_pred)
plt.plot([y.min(), y.max()], [y.min(), y.max()])
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.title("ANN: Actual vs Predicted")
plt.show()

results = pd.DataFrame({
    "Model": ["Random Forest", "SVR", "ANN"],
    "R2": [
        r2_score(y, rf_pred),
        r2_score(y, svr_pred),
        r2_score(y, ann_pred)
    ],
    "RMSE": [
        np.sqrt(mean_squared_error(y, rf_pred)),
        np.sqrt(mean_squared_error(y, svr_pred)),
        np.sqrt(mean_squared_error(y, ann_pred))
    ]
})

results

rf_model.fit(X, y)

rf = rf_model.named_steps["model"]
ohe = rf_model.named_steps["preprocessor"].named_transformers_["cat"]

cat_features = ohe.get_feature_names_out(
    ["Concrete Type", "Cement", "Bacteria"]
)

feature_names = np.concatenate([
    ["Curing Age (Days)", "Log_Bacterial_Concentration"],
    cat_features
])

importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": rf.feature_importances_
}).sort_values(by="Importance", ascending=False)

importance_df

plt.figure(figsize=(8,5))
plt.barh(importance_df["Feature"], importance_df["Importance"])
plt.xlabel("Importance")
plt.title("Feature Importance – Compressive Strength")
plt.gca().invert_yaxis()
plt.show()

from sklearn.model_selection import GridSearchCV, cross_val_predict

"""######Random forest with gridsearch CV"""

rf_pipe = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(random_state=42))
])

rf_param_grid = {
    "model__n_estimators": [300, 500],
    "model__max_depth": [None, 10, 20],
    "model__min_samples_split": [2, 5]
}

rf_grid = GridSearchCV(
    rf_pipe,
    rf_param_grid,
    cv=5,
    scoring="r2",
    n_jobs=-1
)

rf_grid.fit(X, y)

print("Best RF Params:", rf_grid.best_params_)
print("Best RF R2:", rf_grid.best_score_)

svr_pipe = Pipeline([
    ("preprocessor", preprocessor),
    ("model", SVR())
])

svr_param_grid = {
    "model__C": [10, 100, 300],
    "model__epsilon": [0.05, 0.1],
    "model__gamma": ["scale", 0.1]
}

svr_grid = GridSearchCV(
    svr_pipe,
    svr_param_grid,
    cv=5,
    scoring="r2",
    n_jobs=-1
)

svr_grid.fit(X, y)

print("Best SVR Params:", svr_grid.best_params_)
print("Best SVR R2:", svr_grid.best_score_)

ann_pipe = Pipeline([
    ("preprocessor", preprocessor),
    ("model", MLPRegressor(max_iter=5000, random_state=42))
])

ann_param_grid = {
    "model__hidden_layer_sizes": [(32,16), (64,32)],
    "model__alpha": [0.0005, 0.001],
    "model__activation": ["relu"]
}

ann_grid = GridSearchCV(
    ann_pipe,
    ann_param_grid,
    cv=5,
    scoring="r2",
    n_jobs=-1
)

ann_grid.fit(X, y)

print("Best ANN Params:", ann_grid.best_params_)
print("Best ANN R2:", ann_grid.best_score_)

pd.DataFrame({
    "Model": ["Random Forest", "SVR", "ANN"],
    "CV R2": [
        rf_grid.best_score_,
        svr_grid.best_score_,
        ann_grid.best_score_
    ]
})

best_rf  = rf_grid.best_estimator_
best_svr = svr_grid.best_estimator_
best_ann = ann_grid.best_estimator_

y_rf  = cross_val_predict(best_rf,  X, y, cv=5)
y_svr = cross_val_predict(best_svr, X, y, cv=5)
y_ann = cross_val_predict(best_ann, X, y, cv=5)

def ensemble_rmse(weights):
    w_rf, w_svr, w_ann = weights
    y_ens = w_rf*y_rf + w_svr*y_svr + w_ann*y_ann
    return np.sqrt(mean_squared_error(y, y_ens))

constraints = {"type": "eq", "fun": lambda w: sum(w) - 1}
bounds = [(0,1), (0,1), (0,1)]

result = minimize(
    ensemble_rmse,
    x0=[0.4, 0.3, 0.3],
    bounds=bounds,
    constraints=constraints
)

w_rf, w_svr, w_ann = result.x

print("Optimized Weights")
print("RF :", round(w_rf,3))
print("SVR:", round(w_svr,3))
print("ANN:", round(w_ann,3))

y_ensemble = w_rf*y_rf + w_svr*y_svr + w_ann*y_ann

print("ENSEMBLE R2 :", r2_score(y, y_ensemble))
print("ENSEMBLE RMSE:", np.sqrt(mean_squared_error(y, y_ensemble)))

plt.figure()
plt.scatter(y, y_ensemble)
plt.plot([y.min(), y.max()], [y.min(), y.max()])
plt.xlabel("Actual Compressive Strength (MPa)")
plt.ylabel("Predicted Compressive Strength (MPa)")
plt.title("Optimized ANN + SVR + RF Ensemble")
plt.show()

best_rf   # Random Forest pipeline
best_svr  # SVR pipeline
best_ann  # ANN pipeline

from sklearn.model_selection import cross_val_predict

y_rf  = cross_val_predict(best_rf,  X, y, cv=5)
y_svr = cross_val_predict(best_svr, X, y, cv=5)
y_ann = cross_val_predict(best_ann, X, y, cv=5)

from scipy.optimize import minimize
from sklearn.metrics import mean_squared_error
import numpy as np

def ensemble_rmse(weights):
    w_rf, w_svr, w_ann = weights
    y_ensemble = (
        w_rf  * y_rf +
        w_svr * y_svr +
        w_ann * y_ann
    )
    return np.sqrt(mean_squared_error(y, y_ensemble))

constraints = {"type": "eq", "fun": lambda w: w[0] + w[1] + w[2] - 1}
bounds = [(0, 1), (0, 1), (0, 1)]

result = minimize(
    ensemble_rmse,
    x0=[0.33, 0.33, 0.34],  # initial guess
    bounds=bounds,
    constraints=constraints
)

w_rf, w_svr, w_ann = result.x

print("Optimized Ensemble Weights")
print("Random Forest :", round(w_rf, 3))
print("SVR           :", round(w_svr, 3))
print("ANN           :", round(w_ann, 3))

y_ensemble = (
    w_rf  * y_rf +
    w_svr * y_svr +
    w_ann * y_ann
)

from sklearn.metrics import r2_score

print("ENSEMBLE R2   :", r2_score(y, y_ensemble))
print("ENSEMBLE RMSE :", np.sqrt(mean_squared_error(y, y_ensemble)))

import matplotlib.pyplot as plt

plt.figure()
plt.scatter(y, y_ensemble)
plt.plot([y.min(), y.max()], [y.min(), y.max()])
plt.xlabel("Actual Compressive Strength (MPa)")
plt.ylabel("Predicted Compressive Strength (MPa)")
plt.title("Optimized ANN + SVR + RF Ensemble")
plt.show()



















days_df = pd.read_csv("/content/sample_data/days_.csv")
days_df

df.isnull().sum()

df=df.dropna()

FIXED_CEMENT = "OPC 53 (UltraTech)"
FIXED_BACTERIA = "Bacillus subtilis"
FIXED_BACTERIAL_CONC = np.log10(1_000_000)  # same as training

# 1. Clean days_df by dropping the last two rows (aggregates)
days_df_cleaned = days_df.iloc[:-2].copy()

# 2. Melt days_df to long format
id_vars = ['Sample No']
value_vars = [col for col in days_df_cleaned.columns if col not in id_vars]

melted_days_df = days_df_cleaned.melt(id_vars=id_vars, value_vars=value_vars,
                                      var_name='Curing_Age_Type', value_name='Compressive Strength (MPa)')

# 3. Extract Curing Age (Days) and Concrete Type
melted_days_df['Curing Age (Days)'] = melted_days_df['Curing_Age_Type'].apply(lambda x: int(x.split(' ')[0]))
melted_days_df['Concrete Type Raw'] = melted_days_df['Curing_Age_Type'].apply(lambda x: x.split(' ')[1])

# Map 'N' to 'Normal Concrete' and 'BC' to 'Bacterial Concrete'
type_mapping = {'N': 'Normal Concrete', 'BC': 'Bacterial Concrete'}
melted_days_df['Concrete Type'] = melted_days_df['Concrete Type Raw'].map(type_mapping)

# 4. Filter for 'Normal Concrete' data
normal_concrete_data = melted_days_df[melted_days_df['Concrete Type'] == 'Normal Concrete'].copy()

# Ensure sorted by Curing Age and then Sample No to maintain order
normal_concrete_data = normal_concrete_data.sort_values(by=['Curing Age (Days)', 'Sample No']).reset_index(drop=True)

# Construct normal_input DataFrame
normal_input = pd.DataFrame({
    "Concrete Type": ["Normal Concrete"] * len(normal_concrete_data),
    "Curing Age (Days)": normal_concrete_data["Curing Age (Days)"],
    "Cement": [FIXED_CEMENT] * len(normal_concrete_data),
    "Bacteria": ["Control"] * len(normal_concrete_data), # Assuming 'Control' for normal concrete without added bacteria
    "Log_Bacterial_Concentration": [0.0] * len(normal_concrete_data)
})

# Extract y_normal_exp
y_normal_exp = normal_concrete_data['Compressive Strength (MPa)']

bacterial_concrete_data = melted_days_df[melted_days_df['Concrete Type'] == 'Bacterial Concrete'].copy()

# Ensure sorted by Curing Age and then Sample No to maintain order
bacterial_concrete_data = bacterial_concrete_data.sort_values(by=['Curing Age (Days)', 'Sample No']).reset_index(drop=True)

bacterial_input = pd.DataFrame({
    "Concrete Type": ["Bacterial Concrete"] * len(bacterial_concrete_data),
    "Curing Age (Days)": bacterial_concrete_data["Curing Age (Days)"],
    "Cement": [FIXED_CEMENT] * len(bacterial_concrete_data),
    "Bacteria": [FIXED_BACTERIA] * len(bacterial_concrete_data),
    "Log_Bacterial_Concentration": [FIXED_BACTERIAL_CONC] * len(bacterial_concrete_data)
})

y_bacterial_exp = bacterial_concrete_data["Compressive Strength (MPa)"]

y_normal_pred = best_rf.predict(normal_input)
y_bacterial_pred = best_rf.predict(bacterial_input)

from sklearn.metrics import mean_absolute_error

print("NORMAL CONCRETE")
print("MAE :", mean_absolute_error(y_normal_exp, y_normal_pred))

print("\nBACTERIAL CONCRETE")
print("MAE :", mean_absolute_error(y_bacterial_exp, y_bacterial_pred))

plt.figure(figsize=(8,6))

# Normal concrete
plt.plot(normal_concrete_data["Curing Age (Days)"].unique(), y_normal_exp.groupby(normal_concrete_data["Curing Age (Days)"]).mean(), 'o-', label="Experimental Normal")
plt.plot(normal_concrete_data["Curing Age (Days)"].unique(), y_normal_pred.reshape(normal_concrete_data["Curing Age (Days)"].nunique(), -1).mean(axis=1), 's--', label="ML Predicted Normal")

# Bacterial concrete
plt.plot(bacterial_concrete_data["Curing Age (Days)"].unique(), y_bacterial_exp.groupby(bacterial_concrete_data["Curing Age (Days)"]).mean(), 'o-', label="Experimental Bacterial")
plt.plot(bacterial_concrete_data["Curing Age (Days)"].unique(), y_bacterial_pred.reshape(bacterial_concrete_data["Curing Age (Days)"].nunique(), -1).mean(axis=1), 's--', label="ML Predicted Bacterial")

plt.xlabel("Curing Age (Days)")
plt.ylabel("Compressive Strength (MPa)")
plt.title("Experimental vs ML Prediction (Unseen Validation)")
plt.legend()
plt.grid(True)
plt.show()

comparison_df = pd.DataFrame({
    "Curing Age (Days)": normal_concrete_data["Curing Age (Days)"].unique(),
    "Exp_Normal_Mean": y_normal_exp.groupby(normal_concrete_data["Curing Age (Days)"]).mean(),
    "ML_Normal_Mean": y_normal_pred.reshape(normal_concrete_data["Curing Age (Days)"].nunique(), -1).mean(axis=1),
    "Exp_Bacterial_Mean": y_bacterial_exp.groupby(bacterial_concrete_data["Curing Age (Days)"]).mean(),
    "ML_Bacterial_Mean": y_bacterial_pred.reshape(bacterial_concrete_data["Curing Age (Days)"].nunique(), -1).mean(axis=1)
})

print(comparison_df)

# Normal concrete
pred_rf_n  = best_rf.predict(normal_input)
pred_svr_n = best_svr.predict(normal_input)
pred_ann_n = best_ann.predict(normal_input)

# Bacterial concrete
pred_rf_b  = best_rf.predict(bacterial_input)
pred_svr_b = best_svr.predict(bacterial_input)
pred_ann_b = best_ann.predict(bacterial_input)

# Ensemble prediction
pred_ens_normal = (
    w_rf  * pred_rf_n +
    w_svr * pred_svr_n +
    w_ann * pred_ann_n
)

pred_ens_bacterial = (
    w_rf  * pred_rf_b +
    w_svr * pred_svr_b +
    w_ann * pred_ann_b
)

from sklearn.metrics import mean_absolute_error

print("ENSEMBLE – NORMAL CONCRETE")
print("MAE:", mean_absolute_error(y_normal_exp, pred_ens_normal))

print("\nENSEMBLE – BACTERIAL CONCRETE")
print("MAE:", mean_absolute_error(y_bacterial_exp, pred_ens_bacterial))

plt.figure(figsize=(9,6))

# Normal concrete
plt.plot(normal_concrete_data["Curing Age (Days)"].unique(), y_normal_exp.groupby(normal_concrete_data["Curing Age (Days)"]).mean(), 'o-', label="Experimental Normal")
plt.plot(normal_concrete_data["Curing Age (Days)"].unique(), pred_ens_normal.reshape(normal_concrete_data["Curing Age (Days)"].nunique(), -1).mean(axis=1), 's--', label="Ensemble Normal")

# Bacterial concrete
plt.plot(bacterial_concrete_data["Curing Age (Days)"].unique(), y_bacterial_exp.groupby(bacterial_concrete_data["Curing Age (Days)"]).mean(), 'o-', label="Experimental Bacterial")
plt.plot(bacterial_concrete_data["Curing Age (Days)"].unique(), pred_ens_bacterial.reshape(bacterial_concrete_data["Curing Age (Days)"].nunique(), -1).mean(axis=1), 's--', label="Ensemble Bacterial")

plt.xlabel("Curing Age (Days)")
plt.ylabel("Compressive Strength (MPa)")
plt.title("Unseen Validation: Experimental vs Ensemble Prediction")
plt.legend()
plt.grid(True)
plt.show()

comparison_df = pd.DataFrame({
    "Curing Age (Days)": normal_concrete_data["Curing Age (Days)"].unique(),
    "Exp_Normal_Mean": y_normal_exp.groupby(normal_concrete_data["Curing Age (Days)"]).mean(),
    "Ens_Normal_Mean": pred_ens_normal.reshape(normal_concrete_data["Curing Age (Days)"].nunique(), -1).mean(axis=1),
    "Exp_Bacterial_Mean": y_bacterial_exp.groupby(bacterial_concrete_data["Curing Age (Days)"]).mean(),
    "Ens_Bacterial_Mean": pred_ens_bacterial.reshape(bacterial_concrete_data["Curing Age (Days)"].nunique(), -1).mean(axis=1)
})

print(comparison_df)



"""# Task
Refine the existing machine learning pipeline by removing redundant code, fixing the feature importance calculation, consolidating ensemble model evaluation, and evaluating the ensemble model's performance to identify and suggest improvements.

## Remove Redundant df.dropna()

### Subtask:
The `df.isnull().sum()` output indicated no missing values, making the `df.dropna()` call in cell `lJVYSfMXFHE1` unnecessary. This step will remove that redundant line.

## Remove Redundant Imports

### Subtask:
Remove redundant import statements from various cells as they are already handled in the initial imports in `bZ-sV-AZ38c1`.

**Reasoning**:
Remove the redundant import of `cross_val_predict` from cell `km9SLZ3fAPsw` as it has been imported in `bZ-sV-AZ38c1`.
"""

from sklearn.model_selection import GridSearchCV

"""**Reasoning**:
Remove redundant imports from cell `2UmfHUZZCFie` as they are already handled in the initial imports in `bZ-sV-AZ38c1`. This includes `minimize`, `mean_squared_error`, and `numpy`.


"""

def ensemble_rmse(weights):
    w_rf, w_svr, w_ann = weights
    y_ensemble = (
        w_rf  * y_rf +
        w_svr * y_svr +
        w_ann * y_ann
    )
    return np.sqrt(mean_squared_error(y, y_ensemble))

"""**Reasoning**:
Remove the redundant import of `r2_score` from cell `nHr3Bnh7CPyy` as it has been imported in `bZ-sV-AZ38c1`.


"""

y_ensemble = (
    w_rf  * y_rf +
    w_svr * y_svr +
    w_ann * y_ann
)

print("ENSEMBLE R2   :", r2_score(y, y_ensemble))
print("ENSEMBLE RMSE :", np.sqrt(mean_squared_error(y, y_ensemble)))

"""**Reasoning**:
Remove the redundant import of `matplotlib.pyplot` from cell `WefeUrdmCTOW` as it has been imported in `bZ-sV-AZ38c1`.


"""

plt.figure()
plt.scatter(y, y_ensemble)
plt.plot([y.min(), y.max()], [y.min(), y.max()])
plt.xlabel("Actual Compressive Strength (MPa)")
plt.ylabel("Predicted Compressive Strength (MPa)")
plt.title("Optimized ANN + SVR + RF Ensemble")
plt.show()

"""**Reasoning**:
Remove the redundant import of `mean_absolute_error` from cell `_gCDwY6UGS41` as it has been imported in `bZ-sV-AZ38c1`.


"""

print("NORMAL CONCRETE")
print("MAE :", mean_absolute_error(y_normal_exp, y_normal_pred))

print("\nBACTERIAL CONCRETE")
print("MAE :", mean_absolute_error(y_bacterial_exp, y_bacterial_pred))

"""**Reasoning**:
Remove the redundant import of `mean_absolute_error` from cell `udlV7RMnKHED` as it has been imported in `bZ-sV-AZ38c1`.


"""

print("ENSEMBLE – NORMAL CONCRETE")
print("MAE:", mean_absolute_error(y_normal_exp, pred_ens_normal))

print("\nENSEMBLE – BACTERIAL CONCRETE")
print("MAE:", mean_absolute_error(y_bacterial_exp, pred_ens_bacterial))

"""## Fix Feature Importance Calculation

### Subtask:
The current feature importance calculation in cell `F1ec7_QhAHoG` incorrectly concatenates an empty `cat_features` list, leading to only numerical features being considered. This step will modify the cell to correctly use `rf_model.named_steps["preprocessor"].get_feature_names_out()` to obtain all feature names, including the one-hot encoded categorical features, ensuring an accurate feature importance display.

**Reasoning**:
The current feature importance calculation in cell `F1ec7_QhAHoG` is incorrect because it concatenates an empty `cat_features` list. This step will modify the cell to correctly obtain all feature names (numerical and one-hot encoded categorical features) directly from the `ColumnTransformer` within the `rf_model` pipeline using `rf_model.named_steps["preprocessor"].get_feature_names_out()`. This will ensure an accurate display of feature importances.
"""

rf_model.fit(X, y)

rf = rf_model.named_steps["model"]

# Correctly get all feature names from the preprocessor
feature_names = rf_model.named_steps["preprocessor"].get_feature_names_out()

importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": rf.feature_importances_
}).sort_values(by="Importance", ascending=False)

importance_df

"""**Reasoning**:
The previous attempt to fix the feature importance calculation using `rf_model.named_steps["preprocessor"].get_feature_names_out()` did not correctly include the one-hot encoded categorical features in the output, as observed in the kernel state (Variable #10). This step will implement a more robust method by explicitly obtaining feature names from each transformer within the `ColumnTransformer` (numerical and one-hot encoded categorical features) and concatenating them, ensuring all features are considered for importance calculation.


"""

rf_model.fit(X, y)

rf = rf_model.named_steps["model"]

# Get numerical feature names from the 'num' transformer
num_feature_names = rf_model.named_steps["preprocessor"].named_transformers_["num"].get_feature_names_out()

# Get categorical feature names from the 'cat' transformer
cat_feature_names = rf_model.named_steps["preprocessor"].named_transformers_["cat"].get_feature_names_out(categorical_features)

# Combine all feature names
feature_names = np.concatenate([num_feature_names, cat_feature_names])

importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": rf.feature_importances_
}).sort_values(by="Importance", ascending=False)

importance_df

"""### Fix Feature Importance Calculation (Root Cause Address)

The previous attempts to correctly obtain all feature names for the feature importance calculation have failed because the `OneHotEncoder` (as configured in cell `tQrp37vk_Olr` with `drop="first"`) is not generating any output features for the categorical columns, specifically due to 'Cement' having only one unique value, which, when combined with `drop="first"`, results in no feature being created. Additionally, it appears that other categorical features are also not producing expected features.

To address this and ensure all categorical features are represented in the feature importance display, we need to modify the `OneHotEncoder`'s configuration. We will change the `drop` parameter from `"first"` to `None` so that a feature is generated for every category, allowing them to appear in the feature importance. This change requires modifying the `preprocessor` definition, re-initializing the `rf_model` pipeline, and then re-running the feature importance calculation.

**Reasoning**:
To address the root cause of the missing categorical features in the feature importance calculation, the `OneHotEncoder` configuration needs to be modified. Specifically, changing `drop="first"` to `drop=None` will ensure that all categories, even those with only one unique value, generate a feature. Additionally, `handle_unknown="ignore"` can be removed as it's typically used with `drop="first"` or `drop="if_binary"` to handle unseen categories, but when `drop=None`, it's not directly applicable in the same way for preventing feature dropping.
"""

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_features),
        ("cat", OneHotEncoder(drop=None,
                              categories=[
                                  ['Normal Concrete', 'Bacterial Concrete'],
                                  ['OPC 53 (UltraTech)'],
                                  ['Control', 'Bacillus subtilis']
                              ]),
         categorical_features)
    ]
)

"""**Reasoning**:
The `preprocessor` has been redefined to correctly handle categorical features. Now, the `rf_model` pipeline needs to be re-initialized with this updated `preprocessor` to ensure the changes are applied before re-evaluating feature importance.


"""

rf_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(
        n_estimators=500,
        random_state=42
    ))
])

"""**Reasoning**:
The `rf_model` has been re-initialized with the updated `preprocessor`. Now, to get the correct feature importances, the model needs to be refitted to the data, and then the feature importance calculation needs to be re-run using the corrected method.


"""

rf_model.fit(X, y)

rf = rf_model.named_steps["model"]

# Get numerical feature names from the 'num' transformer
num_feature_names = rf_model.named_steps["preprocessor"].named_transformers_["num"].get_feature_names_out()

# Get categorical feature names from the 'cat' transformer
cat_feature_names = rf_model.named_steps["preprocessor"].named_transformers_["cat"].get_feature_names_out(categorical_features)

# Combine all feature names
feature_names = np.concatenate([num_feature_names, cat_feature_names])

importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": rf.feature_importances_
}).sort_values(by="Importance", ascending=False)

importance_df

"""**Reasoning**:
With the feature importances now correctly calculated and displaying all features (numerical and one-hot encoded categorical), the next step is to visualize these importances using the bar plot as previously done in the notebook. This will provide a clear visual representation of each feature's contribution to the model's predictions.


"""

plt.figure(figsize=(8,5))
plt.barh(importance_df["Feature"], importance_df["Importance"])
plt.xlabel("Importance")
plt.title("Feature Importance – Compressive Strength")
plt.gca().invert_yaxis()
plt.show()

"""## Consolidate Redundant Ensemble Calculations

### Subtask:
Consolidate ensemble cross-validation, weight optimization, and final evaluation code by removing redundant cells and ensuring the essential logic is maintained in designated cells.

### Remove Redundant Ensemble Cross-Validation

**Reasoning**:
Cell `3rMKAtjkCCap` is redundant because the cross-validation predictions for `y_rf`, `y_svr`, and `y_ann` are already calculated and stored in cell `zRP7CITaBLqt`. Removing this cell will streamline the notebook by eliminating duplicate code execution.

### Remove Redundant Ensemble RMSE Function Definition

**Reasoning**:
Cell `2UmfHUZZCFie` is redundant because the `ensemble_rmse` function definition is already present in cell `F68sa4chBNjZ`. Removing this cell will streamline the notebook by eliminating duplicate function definitions.

### Remove Redundant Optimization Constraints and Bounds

**Reasoning**:
Cell `ynEonb_DCICm` is redundant because the `constraints` and `bounds` for the optimization are already defined in cell `F68sa4chBNjZ`. Removing this cell will streamline the notebook by eliminating duplicate variable definitions.

### Remove Redundant Ensemble Weight Optimization

**Reasoning**:
Cell `0oWS06D5CNjU` is redundant because the `minimize` function call for optimizing ensemble weights is already performed in cell `F68sa4chBNjZ`. Removing this cell will streamline the notebook by eliminating duplicate optimization steps.

### Remove Redundant Ensemble Metric Calculation and Printing

**Reasoning**:
Cell `nHr3Bnh7CPyy` is redundant because the calculation of `y_ensemble` and the printing of R2 and RMSE metrics are already handled in cell `XXoqvqEOBP9C`. Removing this cell will streamline the notebook by eliminating duplicate metric calculation and printing.

### Remove Redundant Ensemble Plotting

**Reasoning**:
Cell `WefeUrdmCTOW` is redundant because the plotting of the optimized ensemble results is already performed in cell `wcLAZgqiBR9U`. Removing this cell will streamline the notebook by eliminating duplicate plotting.

## Review Model Performance and Suggest Improvements

### Subtask:
Analyze the performance of the ensemble model, identify its limitations compared to individual models (especially for Normal Concrete), and propose strategies for improvement.

## Summary:

### Data Analysis Key Findings

*   **Code Redundancy Removed:** Several redundant code elements were identified and marked for removal.
    *   An unnecessary `df.dropna()` call was found because the DataFrame had no missing values.
    *   Multiple duplicate `import` statements were removed, streamlining the codebase without affecting functionality.
    *   Redundant cells related to ensemble cross-validation, function definitions, optimization constraints, weight optimization, metric calculation, and plotting were identified for consolidation.
*   **Feature Importance Calculation Corrected:**
    *   The initial feature importance calculation for the Random Forest model was incomplete, failing to include one-hot encoded categorical features.
    *   The root cause was identified as the `OneHotEncoder` configuration using `drop="first"`, which prevented features from being generated for categorical columns with single unique values (e.g., 'Cement').
    *   By changing the `OneHotEncoder`'s `drop` parameter to `None`, the feature importance calculation was successfully corrected.
    *   The most important features identified after the fix include "Curing Age (Days)" and "Log\_Bacterial\_Concentration," along with correctly represented categorical features such as "Concrete Type\_Normal Concrete" and "Concrete Type\_Bacterial Concrete."
*   **Ensemble Model Performance Metrics (After Redundancy Removal):**
    *   The ensemble model achieved an R2 score of approximately 0.862 and an RMSE of approximately 1.764.
    *   For normal concrete, the ensemble model had a Mean Absolute Error (MAE) of 9.986.
    *   For bacterial concrete, the ensemble model had an MAE of 5.521.

### Insights or Next Steps

*   **Improve Model Robustness:** Investigate why `OneHotEncoder(drop="first")` caused issues with categorical features, specifically ensuring that encoding strategies are robust to single-value categories to avoid loss of information in future models.
*   **Review Ensemble Performance for Normal Concrete:** The ensemble model's MAE for normal concrete (9.986) is considerably higher than for bacterial concrete (5.521) and also higher than the individual model's MAE for normal concrete (1.155). This significant disparity suggests the ensemble might not be performing optimally for normal concrete, warranting further investigation into its weighting or the individual models' contributions in that specific segment.
"""