# -*- coding: utf-8 -*-
"""f_all_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12lixDbd-O5j72Z2swHxEeNqydcj6O-QN
"""



"""# Task
Load the flexural strength dataset from `/content/sample_data/f_strength.csv`, preprocess the data, develop and evaluate SVR, DTR, GBR, BRR, ANN, and KRR regression models, compare their performance, interpret the results, and provide a final recommendation for flexural strength prediction.

## Load Data

### Subtask:
Load the flexural strength dataset from `/content/sample_data/f_strength.csv` into a Pandas DataFrame and perform an initial inspection to understand its structure and content.

**Reasoning**:
Load the dataset into a pandas DataFrame and perform initial inspection to understand its structure and content by displaying the first 5 rows, checking data types and non-null values, and generating descriptive statistics.
"""

import pandas as pd

# Load the dataset
df = pd.read_csv('/content/sample_data/f_strength.csv')

# Display the first 5 rows
print("First 5 rows of the DataFrame:")
print(df.head())

# Get a concise summary of the DataFrame
print("\nDataFrame Info:")
df.info()

# Generate descriptive statistics
print("\nDescriptive Statistics:")
print(df.describe())

import numpy as np
from sklearn.svm import SVR
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold, cross_validate, train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import matplotlib.pyplot as plt

# Re-split data to ensure X_train and X_test are DataFrames for the pipeline
# X and y are available from the previous steps as DataFrame and Series respectively.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 2. Initialize an SVR model with default parameters
svr_model = SVR()

# 3. Create a scikit-learn Pipeline that first applies the preprocessor and then the svr_model
# The 'preprocessor' object was defined in the previous step and is available in the kernel state.
svr_pipeline = Pipeline(steps=[('preprocessor', preprocessor), ('regressor', svr_model)])

# 4. Define a cross-validation strategy using KFold
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# 5. Use cross_validate with the svr_pipeline, original X, y, and specified scoring metrics
# The preprocessor within svr_pipeline will handle the transformation of X.
cv_results_svr = cross_validate(svr_pipeline, X, y, cv=kf, scoring=['r2', 'neg_mean_squared_error', 'neg_mean_absolute_error'])

# 6. Calculate the mean R², RMSE, and MAE from the cross-validation results
mean_r2_svr = cv_results_svr['test_r2'].mean()
mean_rmse_svr = np.sqrt(np.abs(cv_results_svr['test_neg_mean_squared_error'])).mean()
mean_mae_svr = np.abs(cv_results_svr['test_neg_mean_absolute_error']).mean()

print(f"SVR Cross-Validation R2: {mean_r2_svr:.4f}")
print(f"SVR Cross-Validation RMSE: {mean_rmse_svr:.4f}")
print(f"SVR Cross-Validation MAE: {mean_mae_svr:.4f}")

# 7. Fit the svr_pipeline to the training data (X_train and y_train are now DataFrames/Series)
svr_pipeline.fit(X_train, y_train)

# 8. Make predictions on the test data (X_test is now a DataFrame)
y_pred_svr = svr_pipeline.predict(X_test)

print("SVR model developed, evaluated with cross-validation, and fitted to training data.")

# 10. Create a scatter plot of y_test (actual values) versus y_pred_svr (predicted values)
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred_svr, alpha=0.6)

# 11. Add a red diagonal line representing perfect predictions (where actual equals predicted)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)

# 12. Label the x-axis as 'Actual Flexural Strength (MPa)' and the y-axis as 'Predicted Flexural Strength (MPa)'
plt.xlabel('Actual Flexural Strength (MPa)')
plt.ylabel('Predicted Flexural Strength (MPa)')

# 13. Add a title to the plot
plt.title('SVR Model: Actual vs. Predicted Flexural Strength')

# 14. Display the plot
plt.grid(True)
plt.show()

"""## Develop and Evaluate DTR Model

### Subtask:
Develop a Decision Tree Regression (DTR) model. Integrate the preprocessing pipeline with the DTR model. Evaluate the model's performance using cross-validation, reporting R², RMSE, and MAE. Generate an 'Actual vs. Predicted' plot to visualize its performance.

**Reasoning**:
The subtask requires developing a Decision Tree Regression (DTR) model, integrating it with the existing preprocessing pipeline, evaluating it using cross-validation, and then fitting it to the training data to make predictions on the test set for an 'Actual vs. Predicted' plot. I will perform all these steps in a single code block.
"""

import numpy as np
from sklearn.tree import DecisionTreeRegressor
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold, cross_validate
import matplotlib.pyplot as plt

# 2. Initialize a DecisionTreeRegressor model with default parameters
dtr_model = DecisionTreeRegressor(random_state=42)

# 3. Create a scikit-learn Pipeline that first applies the preprocessor and then the dtr_model
# The 'preprocessor' object was defined in previous steps and is available in the kernel state.
dtr_pipeline = Pipeline(steps=[('preprocessor', preprocessor), ('regressor', dtr_model)])

# 4. Define a cross-validation strategy using KFold
# The 'kf' object is already defined from the SVR step and can be reused.
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# 5. Use cross_validate with the dtr_pipeline, original X, y, and specified scoring metrics
# The preprocessor within dtr_pipeline will handle the transformation of X.
cv_results_dtr = cross_validate(dtr_pipeline, X, y, cv=kf, scoring=['r2', 'neg_mean_squared_error', 'neg_mean_absolute_error'])

# 6. Calculate the mean R², RMSE, and MAE from the cross-validation results
mean_r2_dtr = cv_results_dtr['test_r2'].mean()
mean_rmse_dtr = np.sqrt(np.abs(cv_results_dtr['test_neg_mean_squared_error'])).mean()
mean_mae_dtr = np.abs(cv_results_dtr['test_neg_mean_absolute_error']).mean()

# 7. Print the mean R², RMSE, and MAE for the DTR model
print(f"DTR Cross-Validation R2: {mean_r2_dtr:.4f}")
print(f"DTR Cross-Validation RMSE: {mean_rmse_dtr:.4f}")
print(f"DTR Cross-Validation MAE: {mean_mae_dtr:.4f}")

# 8. Fit the dtr_pipeline to the training data
# X_train and y_train are DataFrames/Series from previous steps.
dtr_pipeline.fit(X_train, y_train)

# 9. Make predictions on the test data
y_pred_dtr = dtr_pipeline.predict(X_test)

print("DTR model developed, evaluated with cross-validation, and fitted to training data.")

# 10. Create a scatter plot of y_test (actual values) versus y_pred_dtr (predicted values)
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred_dtr, alpha=0.6)

# 11. Add a red diagonal line representing perfect predictions
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)

# 12. Label the x-axis and y-axis
plt.xlabel('Actual Flexural Strength (MPa)')
plt.ylabel('Predicted Flexural Strength (MPa)')

# 13. Add a title to the plot
plt.title('DTR Model: Actual vs. Predicted Flexural Strength')

# 14. Display the plot
plt.grid(True)
plt.show()

"""**Reasoning**:
The subtask requires developing a Gradient Boosting Regressor (GBR) model, integrating it with the existing preprocessing pipeline, evaluating it using cross-validation, and then fitting it to the training data to make predictions on the test set for an 'Actual vs. Predicted' plot. I will perform all these steps in a single code block.


"""

import numpy as np
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold, cross_validate
import matplotlib.pyplot as plt

# 2. Initialize a GradientBoostingRegressor model with default parameters
gbr_model = GradientBoostingRegressor(random_state=42)

# 3. Create a scikit-learn Pipeline that first applies the preprocessor and then the gbr_model
# The 'preprocessor' object was defined in previous steps and is available in the kernel state.
gbr_pipeline = Pipeline(steps=[('preprocessor', preprocessor), ('regressor', gbr_model)])

# 4. Define a cross-validation strategy using KFold
# The 'kf' object is already defined from previous steps and can be reused.
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# 5. Use cross_validate with the gbr_pipeline, original X, y, and specified scoring metrics
# The preprocessor within gbr_pipeline will handle the transformation of X.
cv_results_gbr = cross_validate(gbr_pipeline, X, y, cv=kf, scoring=['r2', 'neg_mean_squared_error', 'neg_mean_absolute_error'])

# 6. Calculate the mean R², RMSE, and MAE from the cross-validation results
mean_r2_gbr = cv_results_gbr['test_r2'].mean()
mean_rmse_gbr = np.sqrt(np.abs(cv_results_gbr['test_neg_mean_squared_error'])).mean()
mean_mae_gbr = np.abs(cv_results_gbr['test_neg_mean_absolute_error']).mean()

# 7. Print the mean R², RMSE, and MAE for the GBR model
print(f"GBR Cross-Validation R2: {mean_r2_gbr:.4f}")
print(f"GBR Cross-Validation RMSE: {mean_rmse_gbr:.4f}")
print(f"GBR Cross-Validation MAE: {mean_mae_gbr:.4f}")

# 8. Fit the gbr_pipeline to the training data
# X_train and y_train are DataFrames/Series from previous steps.
gbr_pipeline.fit(X_train, y_train)

# 9. Make predictions on the test data
y_pred_gbr = gbr_pipeline.predict(X_test)

print("GBR model developed, evaluated with cross-validation, and fitted to training data.")

# 10. Create a scatter plot of y_test (actual values) versus y_pred_gbr (predicted values)
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred_gbr, alpha=0.6)

# 11. Add a red diagonal line representing perfect predictions
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)

# 12. Label the x-axis and y-axis
plt.xlabel('Actual Flexural Strength (MPa)')
plt.ylabel('Predicted Flexural Strength (MPa)')

# 13. Add a title to the plot
plt.title('GBR Model: Actual vs. Predicted Flexural Strength')

# 14. Display the plot
plt.grid(True)
plt.show()

"""## Develop and Evaluate BRR Model

### Subtask:
Develop a Bayesian Ridge Regression (BRR) model. Integrate the preprocessing pipeline with the BRR model. Evaluate the model's performance using cross-validation, reporting R², RMSE, and MAE. Generate an 'Actual vs. Predicted' plot to visualize its performance.

**Reasoning**:

The subtask requires developing a Bayesian Ridge Regression (BRR) model, integrating it with the existing preprocessing pipeline, evaluating it using cross-validation, and then fitting it to the training data to make predictions on the test set for an 'Actual vs. Predicted' plot. I will perform all these steps in a single code block.

**Reasoning**:

The subtask requires developing a Bayesian Ridge Regression (BRR) model, integrating it with the existing preprocessing pipeline, evaluating it using cross-validation, and then fitting it to the training data to make predictions on the test set for an 'Actual vs. Predicted' plot. I will perform all these steps in a single code block.

**Reasoning**:
The previous markdown block provided the reasoning for developing the BRR model. Now, I will implement the Bayesian Ridge Regression model, integrate it with the preprocessing pipeline, evaluate it using cross-validation, fit it to the training data, make predictions, and visualize the results with an 'Actual vs. Predicted' plot, as outlined in the subtask.
"""

import numpy as np
from sklearn.linear_model import BayesianRidge
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold, cross_validate
import matplotlib.pyplot as plt

# 2. Initialize a BayesianRidge model with default parameters
brr_model = BayesianRidge()

# 3. Create a scikit-learn Pipeline that first applies the preprocessor and then the brr_model
# The 'preprocessor' object was defined in previous steps and is available in the kernel state.
brr_pipeline = Pipeline(steps=[('preprocessor', preprocessor), ('regressor', brr_model)])

# 4. Define a cross-validation strategy using KFold
# The 'kf' object is already defined from previous steps and can be reused.
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# 5. Use cross_validate with the brr_pipeline, original X, y, and specified scoring metrics
# The preprocessor within brr_pipeline will handle the transformation of X.
cv_results_brr = cross_validate(brr_pipeline, X, y, cv=kf, scoring=['r2', 'neg_mean_squared_error', 'neg_mean_absolute_error'])

# 6. Calculate the mean R², RMSE, and MAE from the cross-validation results
mean_r2_brr = cv_results_brr['test_r2'].mean()
mean_rmse_brr = np.sqrt(np.abs(cv_results_brr['test_neg_mean_squared_error'])).mean()
mean_mae_brr = np.abs(cv_results_brr['test_neg_mean_absolute_error']).mean()

# 7. Print the mean R², RMSE, and MAE for the BRR model
print(f"BRR Cross-Validation R2: {mean_r2_brr:.4f}")
print(f"BRR Cross-Validation RMSE: {mean_rmse_brr:.4f}")
print(f"BRR Cross-Validation MAE: {mean_mae_brr:.4f}")

# 8. Fit the brr_pipeline to the training data
# X_train and y_train are DataFrames/Series from previous steps.
brr_pipeline.fit(X_train, y_train)

# 9. Make predictions on the test data
y_pred_brr = brr_pipeline.predict(X_test)

print("BRR model developed, evaluated with cross-validation, and fitted to training data.")

# 10. Create a scatter plot of y_test (actual values) versus y_pred_brr (predicted values)
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred_brr, alpha=0.6)

# 11. Add a red diagonal line representing perfect predictions
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)

# 12. Label the x-axis and y-axis
plt.xlabel('Actual Flexural Strength (MPa)')
plt.ylabel('Predicted Flexural Strength (MPa)')

# 13. Add a title to the plot
plt.title('BRR Model: Actual vs. Predicted Flexural Strength')

# 14. Display the plot
plt.grid(True)
plt.show()

"""## Develop and Evaluate ANN Model

### Subtask:
Develop an Artificial Neural Network (ANN) model. Integrate the preprocessing pipeline with the ANN model. Evaluate the model's performance using cross-validation, reporting R², RMSE, and MAE. Generate an 'Actual vs. Predicted' plot to visualize its performance.

**Reasoning**:

To develop the Artificial Neural Network (ANN) model, I will start by importing the necessary libraries from Keras (TensorFlow). I will then define a simple sequential model with a few dense layers and ReLU activation, and compile it with an appropriate optimizer (Adam) and loss function (mean squared error). After defining the ANN model, it will be wrapped in a `KerasRegressor` to make it compatible with scikit-learn's `Pipeline` and `cross_validate` functions. This `KerasRegressor` will then be integrated into a pipeline with the existing `preprocessor`. The model's performance will be evaluated using cross-validation to report R², RMSE, and MAE. Finally, the pipeline will be fitted to the training data, predictions will be made on the test set, and an 'Actual vs. Predicted' plot will be generated to visualize the ANN's performance, following the guidelines provided for previous models.

**Reasoning**:
The previous markdown block provided the reasoning for developing the ANN model. Now, I will implement the Artificial Neural Network model, integrate it with the preprocessing pipeline, evaluate it using cross-validation, fit it to the training data, make predictions, and visualize the results with an 'Actual vs. Predicted' plot, as outlined in the subtask.
"""

pip install --upgrade scikeras

"""## Develop and Evaluate KRR Model

### Subtask:
Develop a Kernel Ridge Regression (KRR) model. Integrate the preprocessing pipeline with the KRR model. Evaluate the model's performance using cross-validation, reporting R², RMSE, and MAE. Generate an 'Actual vs. Predicted' plot to visualize its performance.

**Reasoning**:
The subtask requires developing a Kernel Ridge Regression (KRR) model, integrating it with the existing preprocessing pipeline, evaluating it using cross-validation, and then fitting it to the training data to make predictions on the test set for an 'Actual vs. Predicted' plot. I will perform all these steps in a single code block, following the detailed instructions.
"""

import numpy as np
from sklearn.kernel_ridge import KernelRidge
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold, cross_validate
import matplotlib.pyplot as plt

# 2. Initialize a KernelRidge model with default parameters
krr_model = KernelRidge(alpha=1.0, kernel='rbf')

# 3. Create a scikit-learn Pipeline that first applies the preprocessor and then the krr_model
# The 'preprocessor' object was defined in previous steps and is available in the kernel state.
krr_pipeline = Pipeline(steps=[('preprocessor', preprocessor), ('regressor', krr_model)])

# 4. Define a cross-validation strategy using KFold
# The 'kf' object is already defined from previous steps and can be reused.
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# 5. Use cross_validate with the krr_pipeline, original X, y, and specified scoring metrics
# The preprocessor within krr_pipeline will handle the transformation of X.
cv_results_krr = cross_validate(krr_pipeline, X, y, cv=kf, scoring=['r2', 'neg_mean_squared_error', 'neg_mean_absolute_error'])

# 6. Calculate the mean R², RMSE, and MAE from the cross-validation results
mean_r2_krr = cv_results_krr['test_r2'].mean()
mean_rmse_krr = np.sqrt(np.abs(cv_results_krr['test_neg_mean_squared_error'])).mean()
mean_mae_krr = np.abs(cv_results_krr['test_neg_mean_absolute_error']).mean()

# 7. Print the mean R², RMSE, and MAE for the KRR model
print(f"KRR Cross-Validation R2: {mean_r2_krr:.4f}")
print(f"KRR Cross-Validation RMSE: {mean_rmse_krr:.4f}")
print(f"KRR Cross-Validation MAE: {mean_mae_krr:.4f}")

# 8. Fit the krr_pipeline to the training data
# X_train and y_train are DataFrames/Series from previous steps.
krr_pipeline.fit(X_train, y_train)

# 9. Make predictions on the test data
y_pred_krr = krr_pipeline.predict(X_test)

print("KRR model developed, evaluated with cross-validation, and fitted to training data.")

# 10. Create a scatter plot of y_test (actual values) versus y_pred_krr (predicted values)
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred_krr, alpha=0.6)

# 11. Add a red diagonal line representing perfect predictions
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)

# 12. Label the x-axis and y-axis
plt.xlabel('Actual Flexural Strength (MPa)')
plt.ylabel('Predicted Flexural Strength (MPa)')

# 13. Add a title to the plot
plt.title('KRR Model: Actual vs. Predicted Flexural Strength')

# 14. Display the plot
plt.grid(True)
plt.show()

"""## Model Comparison and Interpretation

### Subtask:
Systematically compare the performance of all developed models using the reported metrics (R², RMSE, MAE). Identify the best-performing model(s) and explain observed performance differences in relation to material behavior, nonlinearity, and data characteristics. Perform feature importance analysis for tree-based models (DTR, GBR) and clearly explain how curing age, concrete type, and bacterial parameters influence flexural strength based on these insights.

**Reasoning**:
I need to compile the performance metrics (R², RMSE, MAE) for all successfully evaluated models (SVR, DTR, GBR, BRR, KRR) and display them in a Pandas DataFrame for easy comparison. The metrics are already available as variables in the kernel state.
"""

import pandas as pd

# Compile the metrics into a dictionary
model_performance = {
    'SVR': {
        'R2': mean_r2_svr,
        'RMSE': mean_rmse_svr,
        'MAE': mean_mae_svr
    },
    'DTR': {
        'R2': mean_r2_dtr,
        'RMSE': mean_rmse_dtr,
        'MAE': mean_mae_dtr
    },
    'GBR': {
        'R2': mean_r2_gbr,
        'RMSE': mean_rmse_gbr,
        'MAE': mean_mae_gbr
    },
    'BRR': {
        'R2': mean_r2_brr,
        'RMSE': mean_rmse_brr,
        'MAE': mean_mae_brr
    },
    'KRR': {
        'R2': mean_r2_krr,
        'RMSE': mean_rmse_krr,
        'MAE': mean_mae_krr
    }
}

# Create a DataFrame from the dictionary
performance_df = pd.DataFrame(model_performance).T

# Sort by R2 (descending) to easily identify best models
performance_df = performance_df.sort_values(by='R2', ascending=False)

print("Model Performance Comparison (Cross-Validation Metrics):")
print(performance_df.round(4))

# Identify best performing model(s)
best_r2_model = performance_df['R2'].idxmax()
best_rmse_model = performance_df['RMSE'].idxmin()
best_mae_model = performance_df['MAE'].idxmin()

print(f"\nBest R2 Score: {best_r2_model} ({performance_df.loc[best_r2_model, 'R2']:.4f})")
print(f"Best RMSE Score: {best_rmse_model} ({performance_df.loc[best_rmse_model, 'RMSE']:.4f})")
print(f"Best MAE Score: {best_mae_model} ({performance_df.loc[best_mae_model, 'MAE']:.4f})")

"""**Reasoning**:
I need to perform feature importance analysis for the tree-based models (DTR and GBR). This involves extracting feature names from the preprocessor and then getting the feature importances from the fitted models within their respective pipelines. I will print the feature importances for both DTR and GBR.


"""

import numpy as np

# Get feature names after preprocessing
# The preprocessor was fitted in the preprocessing step
# It applies PolynomialFeatures and OneHotEncoder
feature_names = preprocessor.get_feature_names_out()

# --- Feature Importance for DTR ---
# The DTR model is the 'regressor' step in the dtr_pipeline
dtr_feature_importances = dtr_pipeline.named_steps['regressor'].feature_importances_

# Create a DataFrame for DTR feature importances for better readability
dtr_importance_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': dtr_feature_importances
}).sort_values(by='Importance', ascending=False)

print("\nDecision Tree Regressor Feature Importances:")
print(dtr_importance_df.round(4))

# --- Feature Importance for GBR ---
# The GBR model is the 'regressor' step in the gbr_pipeline
gbr_feature_importances = gbr_pipeline.named_steps['regressor'].feature_importances_

# Create a DataFrame for GBR feature importances for better readability
gbr_importance_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': gbr_feature_importances
}).sort_values(by='Importance', ascending=False)

print("\nGradient Boosting Regressor Feature Importances:")
print(gbr_importance_df.round(4))

"""### Model Performance Interpretation

From the cross-validation results, we can observe the following:

*   **Best Performing Models**: Both **Gradient Boosting Regressor (GBR)** and **Decision Tree Regressor (DTR)** exhibit the highest R² (around 0.8529) and the lowest RMSE (around 0.2549) and MAE (around 0.2034). This suggests that tree-based ensemble methods and individual decision trees are highly effective for this dataset.
*   **SVR and KRR Performance**: Support Vector Regression (SVR) and Kernel Ridge Regression (KRR) also perform quite well, with R² values around 0.84-0.85, indicating their ability to capture non-linear relationships. Their RMSE and MAE are slightly higher than DTR and GBR but still competitive.
*   **BRR Performance**: Bayesian Ridge Regression (BRR) shows the lowest performance among the evaluated models, with an R² of approximately 0.80 and higher RMSE/MAE. This suggests that a simple linear model with regularization (even Bayesian) might not fully capture the underlying complexities or non-linear patterns present in the data, or that the linear assumptions are not well-suited for the relationships between features and flexural strength.
*   **Non-linearity**: The strong performance of DTR, GBR, SVR, and KRR (all capable of modeling non-linear relationships) compared to BRR (which is essentially linear) strongly indicates that the relationship between the input features and flexural strength is likely non-linear. The polynomial features introduced for 'Curing Age (Days)' likely helped these models, especially the linear-based ones, to better capture some of this non-linearity.

### Feature Importance Analysis for Tree-based Models (DTR and GBR)

The feature importance analysis for DTR and GBR reveals consistent insights:

1.  **Curing Age (Days) (and its polynomial feature)**: By far, the most important features for both DTR and GBR are `num__Curing Age (Days)` and `num__Curing Age (Days)^2`. This indicates that the **curing age is the most critical factor influencing flexural strength**, and its effect is non-linear. As concrete cures, its strength typically increases, but the rate of increase might change over time, which the polynomial feature helps to model.

    *   **DTR**: `Curing Age (Days)` (0.7064) and `Curing Age (Days)^2` (0.1496) account for over 85% of the importance.
    *   **GBR**: `Curing Age (Days)` (0.4631) and `Curing Age (Days)^2` (0.3465) similarly account for a very high proportion of importance.

2.  **Concrete Type**: The categorical features related to `Concrete Type` (`cat__Concrete Type_Normal Concrete` and `cat__Concrete Type_Bacterial Concrete`) also show significant importance, though much less than curing age. This indicates that the **type of concrete (Normal vs. Bacterial) plays a noticeable role in determining flexural strength**.

    *   `Normal Concrete` shows slightly higher importance in DTR, while `Bacterial Concrete` shows slightly higher importance in GBR, but both are considered relevant by both models.

3.  **Cement and Bacteria**: The features `cat__Cement_OPC 53 (UltraTech)` and `cat__Bacteria_Bacillus subtilis` both have an importance of 0.0000 in both DTR and GBR. This suggests that these specific categories for Cement and Bacteria, **as represented in this dataset, do not contribute significantly to the prediction of flexural strength** based on these tree-based models. This could be due to a lack of variation in these features within the dataset (e.g., only one type of cement or bacteria used, as indicated by `df.describe()` earlier showing a constant bacterial concentration), or their effect on flexural strength being negligible compared to curing age and concrete type.

### Conclusion

Overall, the tree-based models (DTR and GBR) provide the best predictive performance for flexural strength. The feature importance analysis clearly highlights that **curing age is the predominant factor affecting flexural strength**, followed by the **type of concrete**. The specific cement and bacterial parameters appear to have a minimal impact within the scope of this dataset and models. This understanding is crucial for practical applications, indicating where to focus efforts for strength optimization or material design.

### Model Performance Interpretation

From the cross-validation results, we can observe the following:

*   **Best Performing Models**: Both **Gradient Boosting Regressor (GBR)** and **Decision Tree Regressor (DTR)** exhibit the highest R² (around 0.8529) and the lowest RMSE (around 0.2549) and MAE (around 0.2034). This suggests that tree-based ensemble methods and individual decision trees are highly effective for this dataset.
*   **SVR and KRR Performance**: Support Vector Regression (SVR) and Kernel Ridge Regression (KRR) also perform quite well, with R² values around 0.84-0.85, indicating their ability to capture non-linear relationships. Their RMSE and MAE are slightly higher than DTR and GBR but still competitive.
*   **BRR Performance**: Bayesian Ridge Regression (BRR) shows the lowest performance among the evaluated models, with an R² of approximately 0.80 and higher RMSE/MAE. This suggests that a simple linear model with regularization (even Bayesian) might not fully capture the underlying complexities or non-linear patterns present in the data, or that the linear assumptions are not well-suited for the relationships between features and flexural strength.
*   **Non-linearity**: The strong performance of DTR, GBR, SVR, and KRR (all capable of modeling non-linear relationships) compared to BRR (which is essentially linear) strongly indicates that the relationship between the input features and flexural strength is likely non-linear. The polynomial features introduced for 'Curing Age (Days)' likely helped these models, especially the linear-based ones, to better capture some of this non-linearity.

### Feature Importance Analysis for Tree-based Models (DTR and GBR)

The feature importance analysis for DTR and GBR reveals consistent insights:

1.  **Curing Age (Days) (and its polynomial feature)**: By far, the most important features for both DTR and GBR are `num__Curing Age (Days)` and `num__Curing Age (Days)^2`. This indicates that the **curing age is the most critical factor influencing flexural strength**, and its effect is non-linear. As concrete cures, its strength typically increases, but the rate of increase might change over time, which the polynomial feature helps to model.

    *   **DTR**: `Curing Age (Days)` (0.7064) and `Curing Age (Days)^2` (0.1496) account for over 85% of the importance.
    *   **GBR**: `Curing Age (Days)` (0.4631) and `Curing Age (Days)^2` (0.3465) similarly account for a very high proportion of importance.

2.  **Concrete Type**: The categorical features related to `Concrete Type` (`cat__Concrete Type_Normal Concrete` and `cat__Concrete Type_Bacterial Concrete`) also show significant importance, though much less than curing age. This indicates that the **type of concrete (Normal vs. Bacterial) plays a noticeable role in determining flexural strength**.

    *   `Normal Concrete` shows slightly higher importance in DTR, while `Bacterial Concrete` shows slightly higher importance in GBR, but both are considered relevant by both models.

3.  **Cement and Bacteria**: The features `cat__Cement_OPC 53 (UltraTech)` and `cat__Bacteria_Bacillus subtilis` both have an importance of 0.0000 in both DTR and GBR. This suggests that these specific categories for Cement and Bacteria, **as represented in this dataset, do not contribute significantly to the prediction of flexural strength** based on these tree-based models. This could be due to a lack of variation in these features within the dataset (e.g., only one type of cement or bacteria used, as indicated by `df.describe()` earlier showing a constant bacterial concentration), or their effect on flexural strength being negligible compared to curing age and concrete type.

### Conclusion

Overall, the tree-based models (DTR and GBR) provide the best predictive performance for flexural strength. The feature importance analysis clearly highlights that **curing age is the predominant factor affecting flexural strength**, followed by the **type of concrete**. The specific cement and bacterial parameters appear to have a minimal impact within the scope of this dataset and models. This understanding is crucial for practical applications, indicating where to focus efforts for strength optimization or material design.

## Final Recommendation

### Subtask:
Based on the comprehensive model comparison and interpretation, either suggest a robust ensemble strategy or provide a strong justification for selecting a single optimal model for flexural strength prediction.

## Final Recommendation

### Subtask:
Based on the comprehensive model comparison and interpretation, either suggest a robust ensemble strategy or provide a strong justification for selecting a single optimal model for flexural strength prediction.

#### Instructions
1. Review the `performance_df` DataFrame to confirm the best-performing model(s) based on R², RMSE, and MAE.
2. Consider the feature importance insights for DTR and GBR. If the top models are tree-based, assess if their interpretability (via feature importance) adds value to the recommendation.
3. Based on the performance metrics and interpretation, determine if a single model clearly stands out or if an ensemble approach (e.g., averaging predictions from the top 2-3 models) would be more robust.
4. Write a concise recommendation for flexural strength prediction, justifying your choice by referencing the performance metrics, the ability to capture non-linearity, and any interpretability benefits, especially regarding the influence of 'Curing Age (Days)' and 'Concrete Type'.

## Final Recommendation

### Subtask:
Based on the comprehensive model comparison and interpretation, either suggest a robust ensemble strategy or provide a strong justification for selecting a single optimal model for flexural strength prediction.

#### Instructions
1. Review the `performance_df` DataFrame to confirm the best-performing model(s) based on R², RMSE, and MAE.
2. Consider the feature importance insights for DTR and GBR. If the top models are tree-based, assess if their interpretability (via feature importance) adds value to the recommendation.
3. Based on the performance metrics and interpretation, determine if a single model clearly stands out or if an ensemble approach (e.g., averaging predictions from the top 2-3 models) would be more robust.
4. Write a concise recommendation for flexural strength prediction, justifying your choice by referencing the performance metrics, the ability to capture non-linearity, and any interpretability benefits, especially regarding the influence of 'Curing Age (Days)' and 'Concrete Type'.

## Final Recommendation

### Subtask:
Based on the comprehensive model comparison and interpretation, either suggest a robust ensemble strategy or provide a strong justification for selecting a single optimal model for flexural strength prediction.

#### Instructions
1. Review the `performance_df` DataFrame to confirm the best-performing model(s) based on R², RMSE, and MAE.
2. Consider the feature importance insights for DTR and GBR. If the top models are tree-based, assess if their interpretability (via feature importance) adds value to the recommendation.
3. Based on the performance metrics and interpretation, determine if a single model clearly stands out or if an ensemble approach (e.g., averaging predictions from the top 2-3 models) would be more robust.
4. Write a concise recommendation for flexural strength prediction, justifying your choice by referencing the performance metrics, the ability to capture non-linearity, and any interpretability benefits, especially regarding the influence of 'Curing Age (Days)' and 'Concrete Type'.

## Final Recommendation

### Subtask:
Based on the comprehensive model comparison and interpretation, either suggest a robust ensemble strategy or provide a strong justification for selecting a single optimal model for flexural strength prediction.

#### Instructions
1. Review the `performance_df` DataFrame to confirm the best-performing model(s) based on R², RMSE, and MAE.
2. Consider the feature importance insights for DTR and GBR. If the top models are tree-based, assess if their interpretability (via feature importance) adds value to the recommendation.
3. Based on the performance metrics and interpretation, determine if a single model clearly stands out or if an ensemble approach (e.g., averaging predictions from the top 2-3 models) would be more robust.
4. Write a concise recommendation for flexural strength prediction, justifying your choice by referencing the performance metrics, the ability to capture non-linearity, and any interpretability benefits, especially regarding the influence of 'Curing Age (Days)' and 'Concrete Type'.

## Final Recommendation

### Subtask:
Based on the comprehensive model comparison and interpretation, either suggest a robust ensemble strategy or provide a strong justification for selecting a single optimal model for flexural strength prediction.

#### Instructions
1. Review the `performance_df` DataFrame to confirm the best-performing model(s) based on R², RMSE, and MAE.
2. Consider the feature importance insights for DTR and GBR. If the top models are tree-based, assess if their interpretability (via feature importance) adds value to the recommendation.
3. Based on the performance metrics and interpretation, determine if a single model clearly stands out or if an ensemble approach (e.g., averaging predictions from the top 2-3 models) would be more robust.
4. Write a concise recommendation for flexural strength prediction, justifying your choice by referencing the performance metrics, the ability to capture non-linearity, and any interpretability benefits, especially regarding the influence of 'Curing Age (Days)' and 'Concrete Type'.

## Final Recommendation

### Subtask:
Based on the comprehensive model comparison and interpretation, either suggest a robust ensemble strategy or provide a strong justification for selecting a single optimal model for flexural strength prediction.

#### Instructions
1. Review the `performance_df` DataFrame to confirm the best-performing model(s) based on R², RMSE, and MAE.
2. Consider the feature importance insights for DTR and GBR. If the top models are tree-based, assess if their interpretability (via feature importance) adds value to the recommendation.
3. Based on the performance metrics and interpretation, determine if a single model clearly stands out or if an ensemble approach (e.g., averaging predictions from the top 2-3 models) would be more robust.
4. Write a concise recommendation for flexural strength prediction, justifying your choice by referencing the performance metrics, the ability to capture non-linearity, and any interpretability benefits, especially regarding the influence of 'Curing Age (Days)' and 'Concrete Type'.

## Final Recommendation

### Subtask:
Based on the comprehensive model comparison and interpretation, either suggest a robust ensemble strategy or provide a strong justification for selecting a single optimal model for flexural strength prediction.

#### Instructions
1. Review the `performance_df` DataFrame to confirm the best-performing model(s) based on R², RMSE, and MAE.
2. Consider the feature importance insights for DTR and GBR. If the top models are tree-based, assess if their interpretability (via feature importance) adds value to the recommendation.
3. Based on the performance metrics and interpretation, determine if a single model clearly stands out or if an ensemble approach (e.g., averaging predictions from the top 2-3 models) would be more robust.
4. Write a concise recommendation for flexural strength prediction, justifying your choice by referencing the performance metrics, the ability to capture non-linearity, and any interpretability benefits, especially regarding the influence of 'Curing Age (Days)' and 'Concrete Type'.

## Final Recommendation

### Subtask:
Based on the comprehensive model comparison and interpretation, either suggest a robust ensemble strategy or provide a strong justification for selecting a single optimal model for flexural strength prediction.

#### Instructions
1. Review the `performance_df` DataFrame to confirm the best-performing model(s) based on R², RMSE, and MAE.
2. Consider the feature importance insights for DTR and GBR. If the top models are tree-based, assess if their interpretability (via feature importance) adds value to the recommendation.
3. Based on the performance metrics and interpretation, determine if a single model clearly stands out or if an ensemble approach (e.g., averaging predictions from the top 2-3 models) would be more robust.
4. Write a concise recommendation for flexural strength prediction, justifying your choice by referencing the performance metrics, the ability to capture non-linearity, and any interpretability benefits, especially regarding the influence of 'Curing Age (Days)' and 'Concrete Type'.

## Final Recommendation

### Subtask:
Based on the comprehensive model comparison and interpretation, either suggest a robust ensemble strategy or provide a strong justification for selecting a single optimal model for flexural strength prediction.

#### Instructions
1. Review the `performance_df` DataFrame to confirm the best-performing model(s) based on R², RMSE, and MAE.
2. Consider the feature importance insights for DTR and GBR. If the top models are tree-based, assess if their interpretability (via feature importance) adds value to the recommendation.
3. Based on the performance metrics and interpretation, determine if a single model clearly stands out or if an ensemble approach (e.g., averaging predictions from the top 2-3 models) would be more robust.
4. Write a concise recommendation for flexural strength prediction, justifying your choice by referencing the performance metrics, the ability to capture non-linearity, and any interpretability benefits, especially regarding the influence of 'Curing Age (Days)' and 'Concrete Type'.

## Final Recommendation

### Subtask:
Based on the comprehensive model comparison and interpretation, either suggest a robust ensemble strategy or provide a strong justification for selecting a single optimal model for flexural strength prediction.

#### Instructions
1. Review the `performance_df` DataFrame to confirm the best-performing model(s) based on R², RMSE, and MAE.
2. Consider the feature importance insights for DTR and GBR. If the top models are tree-based, assess if their interpretability (via feature importance) adds value to the recommendation.
3. Based on the performance metrics and interpretation, determine if a single model clearly stands out or if an ensemble approach (e.g., averaging predictions from the top 2-3 models) would be more robust.
4. Write a concise recommendation for flexural strength prediction, justifying your choice by referencing the performance metrics, the ability to capture non-linearity, and any interpretability benefits, especially regarding the influence of 'Curing Age (Days)' and 'Concrete Type'.

**Reasoning**:
Based on the provided instructions, I need to consolidate the model performance results, analyze feature importances, and then formulate a final recommendation. This code block will combine the previously calculated performance metrics and feature importances to provide a structured comparison and a reasoned recommendation for flexural strength prediction.
"""

import pandas as pd
import numpy as np

# 1. Review the `performance_df` DataFrame
print("\n--- Model Performance Comparison (Cross-Validation Metrics) ---\n")
print(performance_df.round(4))

# Identify best performing model(s) for quick reference
best_r2_model = performance_df['R2'].idxmax()
best_rmse_model = performance_df['RMSE'].idxmin()
best_mae_model = performance_df['MAE'].idxmin()

print(f"\nBest R2 Score: {best_r2_model} ({performance_df.loc[best_r2_model, 'R2']:.4f})")
print(f"Best RMSE Score: {best_rmse_model} ({performance_df.loc[best_rmse_model, 'RMSE']:.4f})")
print(f"Best MAE Score: {best_mae_model} ({performance_df.loc[best_mae_model, 'MAE']:.4f})")

# 2. Consider the feature importance insights for DTR and GBR
print("\n--- Feature Importance for Decision Tree Regressor ---\n")
print(dtr_importance_df.round(4))

print("\n--- Feature Importance for Gradient Boosting Regressor ---\n")
print(gbr_importance_df.round(4))

# 3. Formulate the recommendation
print("\n--- Final Recommendation for Flexural Strength Prediction ---\n")

# The ANN model faced persistent errors and could not be evaluated successfully. Its performance is therefore excluded from this recommendation.

if best_r2_model == 'GBR' and best_rmse_model == 'GBR' and best_mae_model == 'GBR':
    print("Based on the cross-validation metrics (R², RMSE, and MAE), the Gradient Boosting Regressor (GBR) and Decision Tree Regressor (DTR) models demonstrate the best performance, with GBR slightly outperforming DTR across all metrics. Their R² values are approximately 0.8529, RMSE around 0.2549, and MAE around 0.2034, indicating strong predictive capabilities for flexural strength.")
    print("\nBoth GBR and DTR are tree-based ensemble methods, which are excellent at capturing non-linear relationships within the data. Their feature importance analysis reveals consistent insights:")
    print("- 'Curing Age (Days)' (and its polynomial feature) is by far the most significant predictor of flexural strength, highlighting its critical role in concrete development.")
    print("- 'Concrete Type' (Bacterial Concrete vs. Normal Concrete) also shows notable importance, indicating the distinct strength characteristics influenced by bacterial inclusion.")
    print("- Features related to 'Cement' and 'Bacteria' (e.g., 'OPC 53 (UltraTech)', 'Bacillus subtilis') show minimal to zero importance, suggesting that given the current dataset, their specific categories do not significantly differentiate flexural strength beyond the 'Concrete Type' distinction.")
    print("\nGiven the very similar and high performance of GBR and DTR, and their interpretability through feature importance, we recommend the **Gradient Boosting Regressor (GBR)** as the optimal model. GBR generally offers more robust predictions than a single Decision Tree by combining multiple weak learners, making it less prone to overfitting and more generalizable. Its slight edge in metrics, combined with its interpretable feature importance, makes it a reliable choice for predicting flexural strength.")
    print("\nFor increased robustness, an ensemble strategy combining the predictions of GBR and DTR could be considered, though GBR alone is sufficient given its strong performance.")
else:
    print("Further analysis would be required to determine the optimal model or ensemble strategy, as a clear best-performing model did not emerge based on all metrics.")

"""## Final Task

### Subtask:
Summarize the entire machine learning framework, including key findings, the performance of the best model(s), and the final recommendation for flexural strength prediction.

## Summary:

### Q&A
The objective was to summarize the entire machine learning framework for flexural strength prediction, including key findings, model performance, and a final recommendation.

### Data Analysis Key Findings
*   The initial dataset contained 1200 entries and 6 columns. `Flexural Strength (MPa)` had 200 missing values, and `Bacterial Concentration (cells/mL)` was a constant feature (standard deviation of 0).
*   Data preprocessing involved dropping rows with missing `Flexural Strength (MPa)` (reducing entries to 1000), removing the constant `Bacterial Concentration (cells/mL)` column, and applying `PolynomialFeatures` (degree 2) and `StandardScaler` to `Curing Age (Days)`. Categorical features were One-Hot Encoded.
*   The Artificial Neural Network (ANN) model could not be successfully evaluated using cross-validation due to a persistent `AttributeError` related to `scikeras.wrappers.KerasRegressor` and scikit-learn's internal `__sklearn_tags__` method.
*   Performance comparison of the successfully evaluated models (SVR, DTR, GBR, BRR, KRR) revealed:
    *   **Gradient Boosting Regressor (GBR)** and **Decision Tree Regressor (DTR)** achieved the highest R² (0.8529) and lowest RMSE (0.2549) and MAE (0.2034) scores.
    *   Support Vector Regressor (SVR) and Kernel Ridge Regressor (KRR) performed closely, with R² values around 0.84-0.85.
    *   Bayesian Ridge Regressor (BRR) showed the lowest performance with an R² of approximately 0.8029.
*   Feature importance analysis for DTR and GBR consistently identified `Curing Age (Days)` (and its polynomial term) as the most critical factor influencing flexural strength, contributing over 85% of importance in DTR and over 80% in GBR.
*   `Concrete Type` was also found to be a relevant feature. However, specific categories of `Cement` and `Bacteria` had negligible importance (0.0000) in the tree-based models, suggesting minimal impact on flexural strength within this dataset.

### Insights or Next Steps
*   **Recommendation**: The Gradient Boosting Regressor (GBR) is recommended as the optimal model for flexural strength prediction due to its superior performance, ability to capture non-linear relationships, robustness, and interpretability through feature importance.
*   **Further Investigation**: Address the `AttributeError` preventing the ANN model's evaluation, potentially by updating libraries or finding alternative `KerasRegressor` wrappers compatible with the current scikit-learn version, to fully assess its potential contribution.
"""