# -*- coding: utf-8 -*-
"""f_ann.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mF9rKK0xOzxOjNGzdPk9bcRooOD8KIez
"""

# Numerical & plotting
import numpy as np
import matplotlib.pyplot as plt

# Data handling
import pandas as pd

# Scikit-learn
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, KFold, cross_validate
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

# Deep Learning
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Keras–Sklearn wrapper
from scikeras.wrappers import KerasRegressor

np.random.seed(42)
tf.random.set_seed(42)

df = pd.read_csv("/content/sample_data/f_strength.csv")
df.head()

df.info()
df.describe()
df.isnull().sum()

X = df.drop("Flexural Strength (MPa)", axis=1)
y = df["Flexural Strength (MPa)"]

num_features = X.select_dtypes(include=np.number).columns
cat_features = X.select_dtypes(exclude=np.number).columns

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), num_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), cat_features)
    ]
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

def create_ann_model(n_features):
    model = Sequential([
        Dense(64, activation="relu", input_shape=(n_features,)),
        Dense(32, activation="relu"),
        Dense(16, activation="relu"),
        Dense(1, activation="linear")
    ])
    model.compile(optimizer="adam", loss="mse")
    return model

ann_model = KerasRegressor(
    model=create_ann_model,
    model__n_features=X_train.shape[1],
    epochs=100,
    batch_size=32,
    verbose=0,
    random_state=42
)

ann_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", ann_model)
])

kf = KFold(n_splits=5, shuffle=True, random_state=42)



mean_r2 = cv_results["test_r2"].mean()
mean_rmse = np.sqrt(-cv_results["test_neg_mean_squared_error"]).mean()
mean_mae = -cv_results["test_neg_mean_absolute_error"].mean()

print(f"ANN CV R2   : {mean_r2:.4f}")
print(f"ANN CV RMSE : {mean_rmse:.4f}")
print(f"ANN CV MAE  : {mean_mae:.4f}")

X_train_processed = preprocessor.fit_transform(X_train, y_train)
n_features_processed = X_train_processed.shape[1]
print(f"Number of features after preprocessing: {n_features_processed}")

ann_model = KerasRegressor(
    model=create_ann_model,
    model__n_features=n_features_processed,
    epochs=100,
    batch_size=32,
    verbose=0,
    random_state=42
)

ann_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", ann_model)
])

cv_results = cross_validate(
    ann_pipeline,
    X_clean,
    y_clean,
    cv=kf,
    scoring=["r2", "neg_mean_squared_error", "neg_mean_absolute_error"]
)

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

def create_ann_model(n_features):
    model = Sequential([
        Input(shape=(n_features,)), # Use Input layer explicitly
        Dense(64, activation="relu"),
        Dense(32, activation="relu"),
        Dense(16, activation="relu"),
        Dense(1, activation="linear")
    ])
    model.compile(optimizer="adam", loss="mse")
    return model

ann_model = KerasRegressor(
    model=create_ann_model,
    model__n_features=n_features_processed,
    epochs=100,
    batch_size=32,
    verbose=0,
    random_state=42
)

ann_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", ann_model)
])

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

def create_ann_model(n_features):
    model = Sequential([
        Input(shape=(n_features,), dtype="float32"), # Use Input layer explicitly with dtype
        Dense(64, activation="relu"),
        Dense(32, activation="relu"),
        Dense(16, activation="relu"),
        Dense(1, activation="linear")
    ])
    model.compile(optimizer="adam", loss="mse")
    return model

ann_model = KerasRegressor(
    model=create_ann_model,
    model__n_features=n_features_processed,
    epochs=100,
    batch_size=32,
    verbose=0,
    random_state=42
)

ann_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", ann_model)
])

ann_model = KerasRegressor(
    model=create_ann_model,
    model__n_features=n_features_processed,
    epochs=100,
    batch_size=32,
    verbose=0,
    random_state=42
)

ann_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", ann_model)
])

cv_results = cross_validate(
    ann_pipeline,
    X_clean,
    y_clean,
    cv=kf,
    scoring=["r2", "neg_mean_squared_error", "neg_mean_absolute_error"]
)

r2_scores = []
mse_scores = []
mae_scores = []

for train_index, test_index in kf.split(X_clean, y_clean):
    X_train_fold, X_test_fold = X_clean.iloc[train_index], X_clean.iloc[test_index]
    y_train_fold, y_test_fold = y_clean.iloc[train_index], y_clean.iloc[test_index]

    # Create a new pipeline for each fold to ensure independent fitting
    # and prevent issues with scikeras internal state across folds
    fold_ann_model = KerasRegressor(
        model=create_ann_model,
        model__n_features=n_features_processed,
        epochs=100,
        batch_size=32,
        verbose=0,
        random_state=42
    )
    fold_ann_pipeline = Pipeline([
        ("preprocessor", preprocessor),
        ("regressor", fold_ann_model)
    ])

    fold_ann_pipeline.fit(X_train_fold, y_train_fold)

    # Manually preprocess and predict to bypass sklearn.pipeline.predict's internal checks
    X_test_fold_processed = fold_ann_pipeline.named_steps["preprocessor"].transform(X_test_fold)
    keras_model_fitted = fold_ann_pipeline.named_steps["regressor"].model_
    y_pred_fold = keras_model_fitted.predict(X_test_fold_processed)

    r2_scores.append(r2_score(y_test_fold, y_pred_fold))
    mse_scores.append(mean_squared_error(y_test_fold, y_pred_fold))
    mae_scores.append(mean_absolute_error(y_test_fold, y_pred_fold))

# Store results in a similar dictionary format as cross_validate
cv_results = {
    "test_r2": np.array(r2_scores),
    "test_neg_mean_squared_error": -np.array(mse_scores), # neg for consistency with cross_validate
    "test_neg_mean_absolute_error": -np.array(mae_scores)  # neg for consistency with cross_validate
}

print("Manual cross-validation complete. Results are in cv_results.")

mean_r2 = cv_results["test_r2"].mean()
mean_rmse = np.sqrt(-cv_results["test_neg_mean_squared_error"]).mean()
mean_mae = -cv_results["test_neg_mean_absolute_error"].mean()

print(f"ANN CV R2   : {mean_r2:.4f}")
print(f"ANN CV RMSE : {mean_rmse:.4f}")
print(f"ANN CV MAE  : {mean_mae:.4f}")